Remove isCleared property from RealmResultsChanges
realm/realm-dart pull request #1265
Opened 2023-05-05 07:54 UTC by desistefanova

isCleared should not be available in RealmResultsChanges
Fixes #1189

2023-05-05 18:56 UTC, nirinchev requested changes
This doesn't seem correct to me. You can convert a list to results and subscribe for notifications. I would expect that it to emit `isCleared` correctly.

2023-05-09 08:02 UTC, desistefanova commented
> This doesn't seem correct to me. You can convert a list to results and subscribe for notifications. I would expect that to emit `isCleared` correctly when the underlying list is cleared.

Ok, I will revert these changes and will add a new test. Thank you for noticing this @nirinchev!

2023-05-16 09:03 UTC, nielsenko approved these changes
LGTM

2023-05-22 17:46 UTC, blagoev commented on CHANGELOG.md
> +* `RealmResultsChanges.isCleared` is deprecated. Its value was not set correctly. It is fixed to return true if the results `isEmpty` ([#1265](https://github.com/realm/realm-dart/pull/1265)). We are
```suggestion
* Fixed `RealmResultsChanges.isCleared` which was never set. It now returns `true` if the results collection is empty in the notification callback. This field is also marked as `deprecated` now and will be removed in future. Use `RealmResultsChanges.results.isEmpty` instead.([#1265](https://github.com/realm/realm-dart/pull/1265)). ([#1278](https://github.com/realm/realm-dart/issues/1278)).
```

2023-05-25 06:12 UTC, merged