Fix: Resolve code gen in Flutter version 3.27.1
realm/realm-dart pull request #1814
Opened 2024-12-24 01:57 UTC by haitr

Problem
It fails to start due to incompatibility issues with updated versions of the `analyzer` and `source_span` packages.

Solution
Pin the versions of `analyzer` and `source_span` packages.

Changes
Updated `pubspec.yaml` to fix package versions:
- `analyzer`: pinned to version 6.9.0
- `source_span`: pinned to version 1.8.0

2024-12-24 01:59 UTC, haitr commented
@cla-bot check

2024-12-27 20:48 UTC, victorcode1 commented
This needs to be resolved

2024-12-30 14:17 UTC, nirinchev requested changes
I think this can only be merged as a short-term fix - pinning the analyzer package like that can cause incompatibilities with other generators that may require different versions.

As far as I understand, the failure reported in https://github.com/realm/realm-dart/issues/1813 is due to `element3` being added to `DartType` - could we instead of pinning the analyzer, provide a `noSuchMethod` implementation that returns `never`? Or does this break in a different way?

2025-01-02 13:34 UTC, closed without merging

2025-01-06 07:53 UTC, haitr commented
@nirinchev Agreed. #1815 came up with the better implementation than mine.