return from write
realm/realm-dart pull request #294
Opened 2022-03-14 12:05 UTC by desistefanova

Return result from write method callback. Fixes #67

2022-03-14 16:24 UTC, nielsenko approved these changes

2022-03-24 10:26 UTC, blagoev requested changes

2022-03-24 10:26 UTC, blagoev commented on lib/src/realm_class.dart
> +  TResult write<TResult>(TResult Function() writeCallback) {
I suggest we use `T` here.

2022-03-24 10:26 UTC, blagoev commented on lib/src/realm_class.dart
> +  TResult write<TResult>(TResult Function() writeCallback) {
```suggestion
  T write<T>(T Function() writeCallback) {
```

2022-03-24 10:26 UTC, blagoev commented on test/realm_test.dart
> +  test('Realm write returns added object', () {
```suggestion
  test('Realm write returns result', () {
```

2022-03-24 15:08 UTC, desistefanova commented on lib/src/realm_class.dart
> +  TResult write<TResult>(TResult Function() writeCallback) {
done

2022-03-25 13:46 UTC, blagoev approved these changes

2022-03-25 14:43 UTC, merged