Consolidate on single config.yaml file
realm/realm-dart pull request #314
Opened 2022-03-25 12:48 UTC by nielsenko

One File to rule them all, One File to find them, One File to bring them all, and in the darkness bind them,

2022-03-25 15:17 UTC, blagoev requested changes
Are we sure this works for all platforms. Does this work on Linux? I see that right now it has some custom paths which should be changed to a generic one, but still it needs different config than macos.

2022-03-25 16:03 UTC, nielsenko commented
> Are we sure this works for all platforms. Does this work on Linux? I see that right now it has some custom paths which should be changed to a generic one, but still it needs different config than macos.

Assuming you have clang 11 lib installed correctly. Fx, on ubuntu: 
```
sudo apt-get install libclang-11-dev
```

2022-03-28 08:46 UTC, blagoev commented
@nielsenko I don't mind the change in this case. Could you update che README.md in ffigen with the these details about Linux.

2022-03-28 12:22 UTC, blagoev approved these changes

2022-03-29 06:10 UTC, merged