Fail generator tests if there are uncommitted changes
realm/realm-dart pull request #449
Opened 2022-03-30 14:26 UTC by nirinchev

This will fail the CI Build if there are uncommitted changes after the generator runs.

2022-03-30 22:13 UTC, nirinchev commented
The CI failures are unrelated to this change and are due to vcpkg not being able to verify the sha1 of 7zip.

2022-03-31 08:56 UTC, blagoev commented
How can we tell that, it says can not find the artifact

2022-03-31 09:03 UTC, blagoev requested changes

2022-03-31 09:04 UTC, nirinchev commented
This is the actual failure: https://github.com/realm/realm-dart/runs/5761745505?check_suite_focus=true. The windows build script doesn't return the correct error code if something fails, which is why the step assumes it was succesful.

2022-03-31 09:05 UTC, nirinchev commented on .github/workflows/pr.yml
> +        working-directory: ./flutter/realm_flutter/example/
We run it in line 554.

2022-03-31 14:46 UTC, nirinchev commented on .github/workflows/pr.yml
> +        working-directory: ./flutter/realm_flutter/example/
I noticed deleting the .g.dart files removes `main.g.dart` and that doesn't get regenerated if I run `build_runner build` inside the repo root which is why this is here.

2022-04-07 13:03 UTC, blagoev commented on .github/workflows/pr.yml
> +        working-directory: ./flutter/realm_flutter/example/
I see

2022-04-07 13:24 UTC, nirinchev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
This is necessary to run the generator in `realm_flutter/example` which will regenerate `main.g.dart`.

2022-04-07 22:07 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
that seems strange. let me test this.

2022-04-07 22:10 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
It seems it should be working without this step since we are using `dart run` instead of `flutter run`

2022-04-07 22:14 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
Yes indeed its required. I suggest we remove the `Setup Dart SDK` step above

2022-04-07 22:15 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
and move the `Setup Flutter` to its place

2022-04-07 22:16 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
on line 543. (could not put comments on unchanged lines)

2022-04-07 22:16 UTC, blagoev commented on .github/workflows/pr.yml
> +      - name: Setup Flutter
this will help speed up the job

2022-04-08 18:41 UTC, blagoev approved these changes

2022-04-08 21:35 UTC, merged