Gc handles
realm/realm-dart pull request #456
Opened 2022-04-01 12:24 UTC by nielsenko

Using gc-handles instead of per-function trampolines.

2022-04-01 12:51 UTC, fealebenpae approved these changes
I like PRs that delete more code than they add 😁 
This makes complete sense to me, and it's going to make writing new callback-heavy code much nicer. However, should we add an option to select between a weak or a strong reference?

2022-04-11 08:17 UTC, blagoev requested changes

2022-04-11 08:17 UTC, blagoev commented on lib/src/native/realm_core.dart
> +        final changesHandle = RealmObjectChangesHandle._(_realmLib.realm_clone(data.cast()).cast());
realm_clone should be invoked with tryGetPointer and could return `null` which we should check

2022-04-11 08:17 UTC, blagoev commented on lib/src/native/realm_core.dart
> +        final changesHandle = RealmCollectionChangesHandle._(_realmLib.realm_clone(data.cast()).cast());
realm_clone result should be checked. See my other comment on that

2022-04-11 08:17 UTC, blagoev commented on lib/src/native/realm_core.dart
> +    if (controller is NotificationsController) {
previously we were debug asserting this is a `NotificationController` instance

2022-04-11 08:17 UTC, blagoev commented on src/realm_dart.cpp
> +RLM_API Dart_Handle gc_handle_deref(void* handle) {
```suggestion
RLM_API Dart_Handle gc_handle_to_object(void* handle) {
```

2022-04-11 08:17 UTC, blagoev commented on src/realm_dart.cpp
> +RLM_API Dart_Handle gc_handle_deref(void* handle) {
A small rename to better reflect the action's result and intent

2022-04-11 08:17 UTC, blagoev commented on src/realm_dart.cpp
> +    Dart_PersistentHandle m_hardHandle; // used to pin dart object from native side, if needed
```suggestion
```

2022-04-11 08:17 UTC, blagoev commented on lib/src/native/realm_core.dart
> +    if (controller is NotificationsController) {
We are removing the debug assertion for `NotificationsController` instance

2022-04-11 16:54 UTC, desistefanova commented on lib/src/native/realm_core.dart
>        controller.onError(RealmError("Error handling collection change notifications. Error: $e"));
```suggestion
      controller.onError(RealmError("Error handling object change notifications. Error: $e"));
```

2022-04-11 16:57 UTC, merged