Allow nullable PKs
realm/realm-dart pull request #459
Opened 2022-04-06 13:23 UTC by nirinchev

Fixes #458

2022-04-06 13:36 UTC, nielsenko approved these changes

2022-04-12 18:55 UTC, blagoev requested changes
I would like to have a discussion about this offline.

2022-04-28 19:49 UTC, nirinchev commented
@blagoev did you get a chance to get buy-in from @ianpward on not supporting nullable PKs in the dart SDK? If so, I propose we close the PR and we can always reopen if user requests come in.

2022-04-29 09:42 UTC, blagoev commented
I converted to draft. If we close it someone might delete the branch. Let's keep it for a while. I know dangling PRs are not great but...

2022-08-17 14:10 UTC, closed without merging