CMake presets and other improvements
realm/realm-dart pull request #514
Opened 2022-04-27 14:38 UTC by fealebenpae

2022-04-29 09:33 UTC, blagoev requested changes

2022-04-29 09:33 UTC, blagoev commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.21)
we need to mention this in the readme

2022-05-04 17:29 UTC, nirinchev commented on flutter/realm_flutter/ios/realm.podspec
> +  s.vendored_frameworks       = 'realm_dart.xcframework'
We use `realm_dart` everywhere else, so I think it's better to be consistent.

2022-05-04 17:35 UTC, fealebenpae commented on src/CMakeLists.txt
> +# Force the linker to include all symbols from RealmFFIStatic. realm-dart resolves them at runtime, so the linker considers them unused.
It's exposing only the C API functions, not all of Core. I haven't measured the file size difference, but it should be negligible.

2022-05-04 17:36 UTC, fealebenpae commented on src/realm.build.use.ccache.cmake
> +    configure_file("${CMAKE_SOURCE_DIR}/scripts/launch-c.in" "${CMAKE_BINARY_DIR}/launch-c")
Good point, I will make a merge commit.

2022-05-04 19:29 UTC, blagoev approved these changes
We better mention that ANDROID_NDK path should be special on Windows. Not sure how this will behave on CI but also on other dev's machines will fail with no clear explanation.

2022-05-05 11:47 UTC, nielsenko approved these changes

2022-05-05 12:12 UTC, merged