Remove the toDart extension method from realm_string_t
realm/realm-dart pull request #585
Opened 2022-05-18 12:57 UTC by nielsenko

2022-05-18 12:57 UTC, nielsenko commented
Do you really prefer this?

2022-05-19 06:01 UTC, blagoev approved these changes

2022-05-19 06:29 UTC, blagoev requested changes
lets not merge this PR.

2022-05-19 16:33 UTC, desistefanova approved these changes

2022-05-20 05:42 UTC, closed without merging