Add realm_dart_http_request_callback trampoline
realm/realm-dart pull request #640
Opened 2022-06-01 17:57 UTC by nielsenko

2022-06-02 10:22 UTC, fealebenpae requested changes
What about the change we discussed yesterday about making the Dart `_request_callback` consider the `body_size` member of the `realm_http_request_t` struct when converting the body bytes into a Dart string?

2022-06-02 10:22 UTC, fealebenpae commented on src/realm_dart_sync.cpp
> +using namespace std;
We don't need these.

2022-06-02 13:08 UTC, nielsenko commented on src/realm_dart_sync.cpp
> +using namespace std;
Fixed

2022-06-02 14:22 UTC, fealebenpae approved these changes

2022-06-06 11:09 UTC, desistefanova approved these changes

2022-06-07 10:12 UTC, merged