Fix flutter test path to realm_dart.dll for windows
realm/realm-dart pull request #660
Opened 2022-06-08 13:42 UTC by desistefanova

When running flutter tests on windows an error appears that realm_dart.dll can not be loaded. 
It is because executable path for flutter tests is not in the local app directory.
There is no such problem on Linux and MacOS.

2022-06-08 14:13 UTC, blagoev requested changes
This should not be needed. Lets investigate why is this happening.

2022-06-08 15:38 UTC, desistefanova commented
> This should not be needed. Lets investigate why is this happening.

The executable file for Flutter is:
 \realm-dart\flutter\realm_flutter\example\build\windows\runner\Debug\realm_example.exe
and it is able to find the realm_dart.dll by name only.
But when we run the flutter tests the executable file is:
\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe
then realm_dart.dll can not be loaded by name only. We need to pass the whole path from the current folder. "./build/windows/runner/Debug/$binaryName.dll";

2022-06-08 16:18 UTC, nirinchev commented
Why does this work on CI then? 🤔

2022-06-09 11:12 UTC, desistefanova commented
Windows:
![image](https://user-images.githubusercontent.com/95419820/172833914-91fc1f75-31f4-4f9a-9f8c-1635d9c31708.png)

MacOS:
![image](https://user-images.githubusercontent.com/95419820/172833058-a13c2353-a41b-434a-aec1-6e14ed5ed5d4.png)

Linux:
![image](https://user-images.githubusercontent.com/95419820/172832724-a9e57063-f53b-44a1-9943-5496a2cc20a0.png)

2022-08-18 09:09 UTC, desistefanova commented
Linked to a task. Will be implemented in a new PR.

2022-08-18 09:09 UTC, closed without merging