Allow nullable types in collections
realm/realm-dart pull request #708
Opened 2022-07-02 00:30 UTC by nielsenko

2022-09-09 15:03 UTC, desistefanova reviewed
Maybe it is by a reason, but it looks more like refactoring than only supporting nullable in collections with primitives. It would be nice if the hierarchy of classes and mixins was simpler. Maybe after the discussion it will become clearer to me.

2022-09-12 12:20 UTC, nielsenko commented on test/list_test.dart
> +  });
This does not test all the cases tested by the original test case?

2022-09-13 07:30 UTC, blagoev requested changes
I think we are doing too much in this PR. We definitely need to have a discussion about the changes around the generator. I think we are putting too much responsibility into the generator which was designed to be lightweight and something we plan to replace in the future.

2022-09-13 08:53 UTC, nielsenko commented
> I think we are doing too much in this PR. We definitely need to have a discussion about the changes around the generator. I think we are putting too much responsibility into the generator which was designed to be lightweight and something we plan to replace in the future.

There is no more logic in the generator than before, it is just as fast as it has always been. It just lays out the generated code in a smarter way. It allows the runtime to skip work, because more is known compile time. I don't see how this in anyway will make it more difficult to transition to static meta-programming once it lands.

2022-09-14 11:17 UTC, nielsenko commented
This is superseded by #902 and #903 which splits the feature implementation from the refactoring

2022-09-14 11:17 UTC, closed without merging

2023-11-09 05:30 UTC, Shreedhar73 commented
@nielsenko Hello.
Are Nullable types in Collections are only supported for local database ? 

When i try to have a field of Type List<String?> it is throwing sync error.
Invalid schema change (UPLOAD): sync does not support collections of nullable primitives unless using the mixed type  . 

Is it the expected behavour or I am missing something here?

2023-11-09 06:18 UTC, nirinchev commented
That is correct. The server team does plan to eventually add support but it hasn't been a highly requested feature and thus we don't have any timeframe for when we'll get to it. If it's important for your app, definitely reach out to your AE to clarify your requirements.

2023-11-09 11:37 UTC, Shreedhar73 commented
@nirinchev Thanks for Clarification.