Remove extra byte in realm_string_t conversion
realm/realm-dart pull request #918
Opened 2022-09-22 16:46 UTC by nirinchev

WIP

2022-09-22 16:50 UTC, nielsenko approved these changes

2022-09-22 16:58 UTC, nielsenko requested changes
`List<int>.toCharPtr` ends up calling 
```dart
Pointer<Uint8> toUint8Ptr(Allocator allocator) {
    final nativeSize = length + 1;
    final result = allocator<Uint8>(nativeSize);
    final Uint8List native = result.asTypedList(nativeSize);
    native.setAll(0, this); // copy
    native.last = 0; // zero terminate
    return result.cast();
  }
```
i guess that need to be re-considered as well?

2022-09-22 17:00 UTC, desistefanova approved these changes

2022-09-22 21:17 UTC, nirinchev commented
`List<int>.toCharPtr` is mapping to `char*` which needs null termination otherwise we can't infer the length.

2022-09-23 12:14 UTC, blagoev approved these changes
good catch.

2022-09-23 16:01 UTC, merged